# VETORES

Os vetores e as matrizes são estruturas de dados estáticas e que suportam apenas um tipo de dadp. Quando criamos um vetor numpy vazio, por padrão, é criado o tipo *float*. Uma vez definido seu tamanho, não é mais possível alterar. São acessados também oir indices que iniciam em zero(0), ocupam menos espaços na memória que as listas e são mais ráidos também. Para criá-los é necessário importar a bibliotexa numpy.

In [3]:
import numpy as np

vetor = np.array([1,2,3,4,5])   #cria um vetor de inteiros 

In [4]:
vetor

array([1, 2, 3, 4, 5])

In [5]:
type(vetor)

numpy.ndarray

In [6]:
vetor.dtype #retorna o tipo dos dados do vetor

dtype('int32')

In [7]:
vetor1 = np.array([2.5,4.8,8.2])    #cria um vetor float

In [8]:
vetor1.dtype

dtype('float64')

In [9]:
nomes = np.array(['Gustavo','Marisa', 'Leonardo'])

In [10]:
nomes.dtype

dtype('<U8')

In [11]:
vetor

array([1, 2, 3, 4, 5])

### OPERAÇÕES ARITMÉTICAS COM VETOR

In [12]:
vetor + vetor

array([ 2,  4,  6,  8, 10])

In [13]:
vetor * 2

array([ 2,  4,  6,  8, 10])

In [15]:
vet1 = np.array([1,2,3])
vet2 = np.array([4,5,6])

In [16]:
vet1 + vet2

array([5, 7, 9])

In [17]:
vetor

array([1, 2, 3, 4, 5])

In [19]:
vetor[2]    #retorna o valor da posição 2

3

In [21]:
vetor[3] = 50   #sobrepõe a posição 3 com o número 50

In [22]:
vetor

array([ 1,  2,  3, 50,  5])

In [23]:
vetor.sort()    #coloca o vetor em ordem crescente

In [24]:
vetor

array([ 1,  2,  3,  5, 50])

In [26]:
del vetor   #apaga o vetor
vetor

NameError: name 'vetor' is not defined

### CRIAR VETOR COM ARANGE

In [28]:
vetor = np.arange(10)   #cria um vetor com 10 elementos sequenciais 

In [29]:
vetor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### CRIAR UM VETOR COM NÚMEROS ALEATÓRIOS 

In [33]:
import random 

#cria um vetor com 10 números aleatórios dentro da faixa de 0 a 100
vetor1 = np.random.randint(100, size=(10))

In [34]:
vetor1

array([15, 93, 56, 22, 41,  7, 44, 59, 78, 12])

### ALGUMAS FUNÇÕES UTILIZADAS EM VETORES 

In [35]:
np.max(vetor1)  #retorna o maior valor do vetor

93

In [36]:
np.min(vetor1)  #retorna o menor valor do vetor

7

In [37]:
np.mean(vetor1)  #retorna a média aritmética do vetor

42.7

In [38]:
np.sum(vetor1)  #retorna a soma dos valores do vetor

427

In [39]:
#PARA CRIAR UM VETOR VAZIO

vetor3 = np.empty(5)    #cria um vetor float

In [40]:
vetor3

array([2.12199579e-314, 6.95229481e-310, 4.50587869e-321, 4.81693045e-312,
       6.75016541e-296])

In [41]:
vetor3.dtype

dtype('float64')

In [43]:
vetor3[0] = 12
vetor3[1] = 25
vetor3[2] = 458
vetor3[3] = 365
vetor3[4] = 8

In [44]:
vetor3

array([ 12.,  25., 458., 365.,   8.])

### CARREGANDO UM VETOR PELO TECLADO

In [45]:
valores = np.empty(5)   #cria um vetor vazio de tipo float 
for i in range(5):
    valores[i] = input('Numero: ')

print(valores)

[10. 54. 54. 21. 54.]


In [46]:
valores = np.empty(5, dtype='int64')   #cria um vetor vazio de tipo int
for i in range(5):
    valores[i] = input('Numero: ')

print(valores)

[10 25  5 45 36]


In [47]:
valores = np.empty(3, dtype='U4')   #cria um vetor string com tamanho maximo da string sendo 4
for i in range(3):
    valores[i] = input('Numero: ')

print(valores)

['Edua' 'Ana' 'Carl']


In [48]:
valores = np.empty(3, dtype='U10')   #cria um vetor string com tamanho maximo da string sendo 10
for i in range(3):
    valores[i] = input('Numero: ')

print(valores)

['SAS' 'dad' 'das']


### MATRIZES

In [49]:
matriz = np.array([[1,2,3],[4,5,6]])

In [50]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
matriz.shape    #retorna a dimensão da matriz

(2, 3)

In [53]:
matriz[0,2] #retorna o valor da linha zero, coluna dois 

3

In [54]:
#MATRIZ IDENTIDADE

I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [56]:
#MATRIZ DIAGONAL

D = np.diag(np.arange(5))
print(D)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [57]:
#MATRIZ DE ZERO

Z = np.zeros([4,4])
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
#MATRIZ DE UNS

U = np.ones([3,3])
print(U)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [62]:
#MATRIZ DE NÚMEROS ALEATÓRIOS

matriz = np.random.randint(100, size=(5,5))
print(matriz)


[[58 33 22 64 15]
 [13 46 37 49 26]
 [ 0 39 65 71 83]
 [17 32 36 33 81]
 [19 66  8 88 99]]
